"""Turns a list of comparison rows into the README's aggregated summary. Pure string
building (no file I/O), so it can be tested directly. Deliberately drops every number
and ticker from its output - see validation/README.md for why."""

from validation.analysis import AGREEMENT_LABELS, AGREEMENT_ORDER, categorize_agreement

START_MARKER = "<!-- VALIDATION:START (generated by validation/validate.py report - do not edit by hand) -->"
END_MARKER = "<!-- VALIDATION:END -->"


def summarize_by_function(rows):
    """{function: {"matched": n, "close": n, "mismatch": n}, ...}, insertion-ordered
    by each function's first appearance in rows."""
    counts = {}
    for row in rows:
        function = row["function"]
        agreement = categorize_agreement(row["my_value"], row["bloomberg_value"])
        counts.setdefault(function, {key: 0 for key in AGREEMENT_ORDER})
        counts[function][agreement] += 1
    return counts


def build_summary_markdown(rows):
    """The full markdown block, including the START/END markers, ready to splice into
    the README. Reports only counts and agreement levels - no my_value, no
    bloomberg_value, no ticker, so nothing from the Bloomberg terminal appears here."""
    lines = [START_MARKER, ""]
    lines.append("## Bloomberg validation")
    lines.append("")

    if not rows:
        lines.append(
            "No comparisons recorded yet. See [validation/README.md](validation/README.md) "
            "to add one after checking a number against the real Bloomberg terminal."
        )
        lines.append("")
        lines.append(END_MARKER)
        return "\n".join(lines)

    lines.append(
        "Numbers from this app cross-checked by hand against the real Bloomberg terminal. "
        "The comparisons themselves (the actual values) are kept in a private, gitignored "
        "file, never in this repo; only the agreement level is reported here."
    )
    lines.append("")

    counts_by_function = summarize_by_function(rows)
    header = ["Function", "Comparisons"] + [AGREEMENT_LABELS[key] for key in AGREEMENT_ORDER]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "---|" * len(header))

    totals = {key: 0 for key in AGREEMENT_ORDER}
    for function in sorted(counts_by_function):
        counts = counts_by_function[function]
        total = sum(counts.values())
        for key in AGREEMENT_ORDER:
            totals[key] += counts[key]
        row_values = [str(counts[key]) for key in AGREEMENT_ORDER]
        lines.append(f"| `{function}` | {total} | " + " | ".join(row_values) + " |")

    grand_total = sum(totals.values())
    total_row = [str(totals[key]) for key in AGREEMENT_ORDER]
    lines.append(f"| **All** | **{grand_total}** | " + " | ".join(f"**{v}**" for v in total_row))

    dates = sorted(row["date_checked"] for row in rows if row.get("date_checked"))
    if dates:
        lines.append("")
        lines.append(f"Most recent comparison: {dates[-1]}.")

    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)
